### ISSUE TITLE
Use getQ() instead of getP()

### ISSUE THREAD

**Issue by piu130** [tbrixen/u-prove#1]
Shouldn't you use `getQ()` instead of `getP()` on [this](https://github.com/tbrixen/u-prove/blob/master/src/Issuer.java#L39) line?

In the [doc](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/U-Prove20Cryptographic20Specification20V1.1.pdf) you can read in `Figure1 - Verify public key elements` that g0 should be element of gq (not of gp).

**Comment by tbrixen** [comment]
You are absolutely right. Really nice catch! I've fixed this in the commit here https://github.com/tbrixen/u-prove/commit/b21a49163e861d5aecb197615715f044a747a74c.

I've also updated the README with a disclaimer of unfinished code, due to time constraints when this was implemented.
